### PR TITLE
chore: update DashPay and DPNS contracts

### PR DESCRIPTION
**Pull request by thephez**
## Issue being fixed or feature implemented

Testnet contract IDs changed after redeployment

## What was done?

Updated contract IDs

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by shumkov — APPROVED** [review]
👍

**Comment by thephez** [comment]
@shumkov Should the version be bumped in this PR too?

**Review by thephez — COMMENTED** [review]
utACK (on the contract ID change - not sure what the GH workflow branch is supposed to be)

**Review by strophy — DISMISSED** [review]

**Review by shumkov — APPROVED** [review]

**Review by shumkov — APPROVED** [review]
👍

**Pull request merged**
